issue-74
gdljs/gdljs pull request #75
Opened 2018-09-26 21:11 UTC by lordenzo

- Aquí está el draft que se me ocurrió para el template de los core issues, por favor comenten o agreguen dudas para mejorarlo.

2018-11-20 19:44 UTC, rbdr requested changes

2018-11-20 19:44 UTC, rbdr commented on CORE_ISSUE_TEMPLATE.md
> +# Sumario
Resumen suena más real

2018-11-20 19:44 UTC, rbdr commented on CORE_ISSUE_TEMPLATE.md
> +- No más de 5 palabras
No está muy estricto? En que se basa el límite? Podría ser algo como "una oración"?

2018-11-20 19:44 UTC, rbdr commented on CORE_ISSUE_TEMPLATE.md
> +# Background
^Background^Contexto?

2018-11-20 19:44 UTC, rbdr commented on CORE_ISSUE_TEMPLATE.md
> +# Encargado/Encargada
Responsable es neutro

2019-02-27 17:31 UTC, sirgalleto requested changes

2019-02-27 17:31 UTC, sirgalleto commented on CORE_ISSUE_TEMPLATE.md
> +- No más de 5 palabras
+ 1

2020-09-18 16:45 UTC, orlando commented
Voy a cerrar esto, creo que esto lo tenemos que revisar mejor

2020-09-18 16:45 UTC, closed without merging